// <auto-generated />
using MedML.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedML.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203195134_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedML.Models.HeartDiseaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("ChestPainType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chest_pain_type");

                    b.Property<int>("Cholesterol")
                        .HasColumnType("integer")
                        .HasColumnName("cholesterol");

                    b.Property<string>("ExerciseAngina")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise_angina");

                    b.Property<int>("FastingBS")
                        .HasColumnType("integer")
                        .HasColumnName("fasting_bs");

                    b.Property<int>("HeartDisease")
                        .HasColumnType("integer")
                        .HasColumnName("heart_disease");

                    b.Property<int>("MaxHR")
                        .HasColumnType("integer")
                        .HasColumnName("max_hr");

                    b.Property<float>("Oldpeak")
                        .HasColumnType("real")
                        .HasColumnName("oldpeak");

                    b.Property<int>("RestingBP")
                        .HasColumnType("integer")
                        .HasColumnName("resting_bp");

                    b.Property<string>("RestingECG")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resting_ecg");

                    b.Property<string>("ST_Slope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("st_slope");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.HasKey("Id");

                    b.ToTable("heart_disease_records");
                });

            modelBuilder.Entity("MedML.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
